#!/bin/sh

tmux start-server

cd ~/
tmux new-session -d -s Main

tmux new-window -t Main:1 -n monitor
tmux new-window -t Main:2 -n ranger
tmux new-window -t Main:3 -n mocp 
tmux new-window -t Main:4 -n term 
tmux new-window -t Main:5 -n dev 

tmux send-keys -t Main:1 'htop' C-m
tmux send-keys -t Main:2.0 'ranger' C-m
tmux send-keys -t Main:3.0 'mocp' C-m
tmux send-keys -t Main:5.0 'cd ~/ada/dev/;' C-m

tmux select-window -t Main:4

tmux -2 attach-session -t Main
